services:
  postgres:
    networks:
      - bridge
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  bridge:
    driver: bridge

volumes:
  postgres_data:
